### ISSUE TITLE
Tag version or add changelog

### ISSUE THREAD

**Issue by kamaradclimber** [autotraderuk/chef-tuned#3]
Hello,

our team uses [knife-changelog](https://rubygems.org/gems/knife-changelog/versions/0.4.3) to help to upgrade cookbooks.
It requires that versions are either tagged or have a Changelog.md file that is properly updated at each version.

Could you stick to either of this practise?
Thanks a lot.

I am of course available to discuss alternative methods to derive a changelog automatically if you want.

**Comment by davemeekin** [comment]
Hi,

I'll look into the details of this tomorrow. I'm sure we can sort something out quickly.

Thanks,

Dave

**Comment by jmauro** [comment]
Any love for this request?

Regards,
JM

**Comment by davemeekin** [comment]
Hi,

Apologies for the delay, work commitments....
I've versioned the code now and added a CHANGELOG.md.
Is this sufficient now and going forward? or do i need to cut a new release (v1.2.1) from the latest commits and publish this to the chef supermarket?

Regards,

Dave

**Comment by kamaradclimber** [comment]
Release tags are perfect for us.
Thanks a lot @davemeekin !
