### ISSUE TITLE
Enabling tuned profiles in roles/nodes?

### ISSUE THREAD

**Issue by themysteq** [autotraderuk/chef-tuned#4]
I'm not much experienced in chef but is it possible or would not be better if it could be configurated in role? i.e.

```
...
  "chef_type": "role",
  "run_list": [
    "recipe[server::www]",
    "recipe[chef-tuned::virtual-guest]"
  ],
...
```

**Comment by davemeekin** [comment]
I'm not familiar with calling an LWRP in this way. Do you have any examples?

**Comment by davemeekin** [comment]
closing no further comment
